---
# Variables
vars:
  name: "openvpnvm"
  location: "eastus"
  nsg: "{{vars.name}}-nsg"

# Required metadata 
name: "{{ vars.name }}"
resource_group: "cdf_example_{{ vars.name }}"
location: "{{ vars.location }}"

# Provisioner
provisioner: bicep

# Deployment Params
params:
    networkSecurityGroupName: "{{ vars.nsg }}"
    location: "{{ vars.location }}"
    securityRules: 
    - name: 'ssh'
      properties: 
        priority: '1000'
        sourceAddressPrefix: '*'
        protocol: 'Tcp'
        destinationPortRange: '22'
        access: 'Allow'
        direction: 'Inbound'
        sourcePortRange: '*'
        destinationAddressPrefix: '*'
